{% set name = "jaxns" %}
{% set version = "2.6.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaxns-{{ version }}.tar.gz
  sha256: 49ccf9cbbb794b9279da4490ab5e4e4f87d6d629488f59767afda9686abc479c

build:
  noarch: python
  number: 0

requirements:
  host:
    - setuptools >=61.0
    - pip
    - python {{ python_min }}
    - wheel
  run:
    - jax >=0.6.0
    - numpy
    - matplotlib-base
    - python >={{ python_min }}
    - scipy
    - tensorflow-probability

test:
  imports:
    - jaxns
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jaxns.readthedocs.io/en/latest/
  dev_url: https://github.com/Joshuaalbert/jaxns
  summary: Nested Sampling in JAX
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
